# https://docs.travis-ci.com/user/ci-environment/
# trusty - 7.5GB memory and 2 cores
sudo: required
dist: trusty

# travis performs a shallow clone by default, in case of any issues
# that requires full git history, enable this
# before_install: git fetch --unshallow

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

env:
  MAVEN_SKIP_RC=true
  MAVEN_OPTS="-Xmx2g"

# workaround added: https://github.com/travis-ci/travis-ci/issues/4629
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install: true

script: ./bisect-check.bash
